--- #YAML:1.0
name:                Acme-LOLCAT
version:             0.0.3
abstract:            SPEEK LIEK A LOLCATZ
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kent Cowgill <kent@c2group.net>
